# Generated by Django 3.2.9 on 2021-12-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20211213_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateField(default='2021-12-14'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-12-14'),
        ),
    ]
