# Generated by Django 3.2.9 on 2021-12-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20211210_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='insertInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('email', models.TextField(max_length=250)),
                ('mobile', models.TextField(max_length=250)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
    ]
