# Generated by Django 3.2.9 on 2021-12-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_insertinquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='insertInquiry',
            new_name='RegisterUser',
        ),
    ]
