# Generated by Django 3.2.9 on 2021-12-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_rename_insertinquiry_registeruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterUser',
            new_name='Users',
        ),
    ]
