# Generated by Django 3.2.9 on 2021-12-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_auto_20211211_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-name']},
        ),
    ]
